spring:
  application:
    name: user-service
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

database:
  url: ${US_DB_URL}
  username: ${US_DB_USER}
  password: ${US_DB_PASSWORD}
  schema: ${US_DB_SCHEMA}

server:
  port: ${SERVER_INTERNAL_PORT}

file-service:
  uri: ${FILE_SERVICE_URI}
  default-avatar-id: ${DEFAULT_AVATAR_ID}

config:
  jwt:
    secret: ${JWT_SECRET}
    access_token_expiration: ${JWT_ACCESS_EXPIRATION_TIME}
    refresh_token_expiration: ${JWT_REFRESH_EXPIRATION_TIME}
