ALTER TABLE user_to_mentor
    DROP CONSTRAINT fk_user_to_mentor_on_mentor;

ALTER TABLE user_to_mentor
    DROP CONSTRAINT fk_user_to_mentor_on_user;

CREATE TABLE children
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    patronymic VARCHAR(255)                            NOT NULL,
    user_id    BIGINT,
    mentor_id  BIGINT,
    CONSTRAINT pk_children PRIMARY KEY (id)
);

ALTER TABLE children
    ADD CONSTRAINT FK_CHILDREN_ON_MENTOR FOREIGN KEY (mentor_id) REFERENCES users (id);

ALTER TABLE children
    ADD CONSTRAINT FK_CHILDREN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

DROP TABLE user_to_mentor CASCADE;