CREATE TABLE child_to_mentor
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    child_id  BIGINT                                  NOT NULL,
    mentor_id BIGINT,
    CONSTRAINT pk_child_to_mentor PRIMARY KEY (id)
);

ALTER TABLE child_to_mentor
    ADD CONSTRAINT FK_CHILD_TO_MENTOR_ON_CHILD FOREIGN KEY (child_id) REFERENCES children (id);

ALTER TABLE child_to_mentor
    ADD CONSTRAINT FK_CHILD_TO_MENTOR_ON_MENTOR FOREIGN KEY (mentor_id) REFERENCES users (id);