CREATE TABLE telegram_entity
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tg_link VARCHAR(255)                            NOT NULL,
    user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_telegramentity PRIMARY KEY (id)
);

ALTER TABLE telegram_entity
    ADD CONSTRAINT uc_telegramentity_tglink UNIQUE (tg_link);

ALTER TABLE telegram_entity
    ADD CONSTRAINT uc_telegramentity_user UNIQUE (user_id);

ALTER TABLE telegram_entity
    ADD CONSTRAINT FK_TELEGRAMENTITY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);