ALTER TABLE telegram_entity
    DROP CONSTRAINT fk_telegramentity_on_user;

CREATE TABLE telegram_links
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tg_link VARCHAR(255)                            NOT NULL,
    user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_telegramlinks PRIMARY KEY (id)
);

ALTER TABLE telegram_links
    ADD CONSTRAINT uc_telegramlinks_tglink UNIQUE (tg_link);

ALTER TABLE telegram_links
    ADD CONSTRAINT uc_telegramlinks_user UNIQUE (user_id);

ALTER TABLE telegram_links
    ADD CONSTRAINT FK_TELEGRAMLINKS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

DROP TABLE telegram_entity CASCADE;