CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(255)                            NOT NULL,
    last_name     VARCHAR(255)                            NOT NULL,
    patronymic    VARCHAR(255)                            NOT NULL,
    date_of_birth TIMESTAMP WITHOUT TIME ZONE,
    email         VARCHAR(255)                            NOT NULL,
    mobile_number VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    role          SMALLINT                                NOT NULL,
    avatar_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_mobilenumber UNIQUE (mobile_number);