ALTER TABLE user_documents
    DROP CONSTRAINT fk_user_documents_on_user;

CREATE TABLE child_documents
(
    id                                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                            BIGINT                                  NOT NULL,
    snils_number                       VARCHAR(255)                            NOT NULL,
    snils_id                           BIGINT                                  NOT NULL,
    studying_place                     VARCHAR(255)                            NOT NULL,
    studying_certificate_id            BIGINT                                  NOT NULL,
    learning_class                     SMALLINT                                NOT NULL,
    training_ground                    VARCHAR(255)                            NOT NULL,
    additional_studying_certificate_id BIGINT                                  NOT NULL,
    parent_role                        VARCHAR(255)                            NOT NULL,
    consent_to_child_pdp_id            BIGINT                                  NOT NULL,
    birth_certificate_id               BIGINT                                  NOT NULL,
    CONSTRAINT pk_child_documents PRIMARY KEY (id)
);

ALTER TABLE child_documents
    ADD CONSTRAINT uc_child_documents_additionalstudyingcertificateid UNIQUE (additional_studying_certificate_id);

ALTER TABLE child_documents
    ADD CONSTRAINT uc_child_documents_birthcertificateid UNIQUE (birth_certificate_id);

ALTER TABLE child_documents
    ADD CONSTRAINT uc_child_documents_consenttochildpdpid UNIQUE (consent_to_child_pdp_id);

ALTER TABLE child_documents
    ADD CONSTRAINT uc_child_documents_snilsid UNIQUE (snils_id);

ALTER TABLE child_documents
    ADD CONSTRAINT uc_child_documents_snilsnumber UNIQUE (snils_number);

ALTER TABLE child_documents
    ADD CONSTRAINT uc_child_documents_studyingcertificateid UNIQUE (studying_certificate_id);

ALTER TABLE child_documents
    ADD CONSTRAINT uc_child_documents_user UNIQUE (user_id);

ALTER TABLE child_documents
    ADD CONSTRAINT FK_CHILD_DOCUMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

DROP TABLE user_documents CASCADE;