CREATE TABLE mentor_links
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    biscuit VARCHAR(255)                            NOT NULL,
    user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_mentor_links PRIMARY KEY (id)
);

ALTER TABLE mentor_links
    ADD CONSTRAINT uc_mentor_links_biscuit UNIQUE (biscuit);

ALTER TABLE mentor_links
    ADD CONSTRAINT uc_mentor_links_user UNIQUE (user_id);

ALTER TABLE mentor_links
    ADD CONSTRAINT FK_MENTOR_LINKS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);