CREATE TABLE user_documents
(
    id                                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                            BIGINT                                  NOT NULL,
    snils_number                       VARCHAR(255)                            NOT NULL,
    snils_id                           BIGINT                                  NOT NULL,
    studying_place                     VARCHAR(255)                            NOT NULL,
    studying_certificate_id            BIGINT                                  NOT NULL,
    learning_class                     SMALLINT                                NOT NULL,
    training_ground                    VARCHAR(255)                            NOT NULL,
    additional_studying_certificate_id BIGINT                                  NOT NULL,
    parent_role                        SMALLINT                                NOT NULL,
    consent_to_child_pdp_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_documents PRIMARY KEY (id)
);

ALTER TABLE user_documents
    ADD CONSTRAINT uc_user_documents_additionalstudyingcertificateid UNIQUE (additional_studying_certificate_id);

ALTER TABLE user_documents
    ADD CONSTRAINT uc_user_documents_consenttochildpdpid UNIQUE (consent_to_child_pdp_id);

ALTER TABLE user_documents
    ADD CONSTRAINT uc_user_documents_snilsid UNIQUE (snils_id);

ALTER TABLE user_documents
    ADD CONSTRAINT uc_user_documents_snilsnumber UNIQUE (snils_number);

ALTER TABLE user_documents
    ADD CONSTRAINT uc_user_documents_studyingcertificateid UNIQUE (studying_certificate_id);

ALTER TABLE user_documents
    ADD CONSTRAINT uc_user_documents_user UNIQUE (user_id);

ALTER TABLE user_documents
    ADD CONSTRAINT FK_USER_DOCUMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);