CREATE TABLE mentor_documents
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                  BIGINT                                  NOT NULL,
    institution              VARCHAR(255)                            NOT NULL,
    post                     VARCHAR(255)                            NOT NULL,
    consent_to_mentor_pdp_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_mentor_documents PRIMARY KEY (id)
);

ALTER TABLE mentor_documents
    ADD CONSTRAINT uc_mentor_documents_consenttomentorpdpid UNIQUE (consent_to_mentor_pdp_id);

ALTER TABLE mentor_documents
    ADD CONSTRAINT uc_mentor_documents_user UNIQUE (user_id);

ALTER TABLE mentor_documents
    ADD CONSTRAINT FK_MENTOR_DOCUMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);