CREATE TABLE tutor_documents
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                 BIGINT                                  NOT NULL,
    institution             VARCHAR(255)                            NOT NULL,
    post                    VARCHAR(255)                            NOT NULL,
    consent_to_tutor_pdp_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_tutor_documents PRIMARY KEY (id)
);

ALTER TABLE tutor_documents
    ADD CONSTRAINT uc_tutor_documents_consenttotutorpdpid UNIQUE (consent_to_tutor_pdp_id);

ALTER TABLE tutor_documents
    ADD CONSTRAINT uc_tutor_documents_user UNIQUE (user_id);

ALTER TABLE tutor_documents
    ADD CONSTRAINT FK_TUTOR_DOCUMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);