CREATE TABLE expert_documents
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                  BIGINT                                  NOT NULL,
    institution              VARCHAR(255)                            NOT NULL,
    post                     VARCHAR(255)                            NOT NULL,
    consent_to_expert_pdp_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_expert_documents PRIMARY KEY (id)
);

ALTER TABLE expert_documents
    ADD CONSTRAINT uc_expert_documents_consenttoexpertpdpid UNIQUE (consent_to_expert_pdp_id);

ALTER TABLE expert_documents
    ADD CONSTRAINT uc_expert_documents_user UNIQUE (user_id);

ALTER TABLE expert_documents
    ADD CONSTRAINT FK_EXPERT_DOCUMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);