CREATE TABLE jwt_tokens_storage
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    uuid    UUID                                    NOT NULL,
    token   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_jwt_tokens_storage PRIMARY KEY (id)
);

ALTER TABLE jwt_tokens_storage
    ADD CONSTRAINT uc_jwt_tokens_storage_uuid UNIQUE (uuid);

ALTER TABLE jwt_tokens_storage
    ADD CONSTRAINT FK_JWT_TOKENS_STORAGE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);