CREATE TABLE user_to_mentor
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    mentor_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_to_mentor PRIMARY KEY (id)
);

ALTER TABLE user_to_mentor
    ADD CONSTRAINT FK_USER_TO_MENTOR_ON_MENTOR FOREIGN KEY (mentor_id) REFERENCES users (id);

ALTER TABLE user_to_mentor
    ADD CONSTRAINT FK_USER_TO_MENTOR_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);